### ISSUE TITLE
Add yaml representer for Markov

### ISSUE THREAD

**Issue by braraki** [wasserfeder/lomap#3]
We currently only have a hacked version for loading and saving MDPs as YAML files.

**Comment by braraki** [comment]
Also add for FSAs please.

**Comment by wasserfeder** [comment]
Issues should be resolved now. Please test and let me know if saving and loading work for you now. I also added a test script. You should look into it for simple code examples.

**Comment by wasserfeder** [comment]
I consider this issue solved (commit `06df167`).
