### ISSUE TITLE
Not compatible with Python3

### ISSUE THREAD

**Issue by braraki** [wasserfeder/lomap#9]
I made lomap compatible with python 3. It wasn't too bad, there was just one tricky step.

1. use '2to3' (comes with python) to convert lomap scripts to python3.
`/path-to-lomap/lomap$ 2to3 -w -n .`
Note: -w means that 2to3 writes the changes to the files (instead of just printing to terminal) and -n means do not create backup files.
2. The package 'pp' is not python3 compatible. You can get around this by installing pp-1.6.4.4 from [https://www.parallelpython.com/content/view/18/32/](https://www.parallelpython.com/content/view/18/32/) and running `sudo pip install .` in the folder (maybe pip3?) and then adding the path to pp to your PYTHONPATH variable. (see [https://github.com/Kamnitsask/deepmedic/issues/58](https://www.parallelpython.com/content/view/18/32/) for more info)

**Comment by wasserfeder** [comment]
Solved this in PR #17 .
